PalletTown_Text_OakDontGoOut::
    .string "OAK: Hey! Wait!\n"
    .string "Don't go out!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
    .string "OAK: It's unsafe!\n"
    .string "Wild POKéMON live in tall grass!\p"
    .string "You need your own POKéMON for\n"
    .string "your protection.\p"
    .string "I know!\n"
    .string "Here, come with me!$"

PalletTown_Text_RaisingMonsToo::
    .string "I'm raising POKéMON, too.\p"
    .string "When they get strong, they can\n"
    .string "protect me.$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
    .string "Technology is incredible!\p"
    .string "You can now store and recall items\n"
    .string "and POKéMON as data via PC.$"

PalletTown_Text_OakPokemonResearchLab::
    .string "OAK POKéMON RESEARCH LAB$"

PalletTown_Text_PlayersHouse::
    .string "{PLAYER}'s house$"

PalletTown_Text_RivalsHouse::
    .string "{RIVAL}'s house$"

PalletTown_Text_Aliza_NoPokemon::
    .string "Come back when you have a Pokémon!$"

PalletTown_Text_Aliza_BadgeCount::
    .string "Badge count is {STR_VAR_1}.$"

PalletTown_Text_Aliza_AlreadyWon::
    .string "Thanks for the battle! Come back\n"
    .string "when you get the next badge!$"

PalletTown_Text_Aliza_WonAll::
    .string "Good luck with the Elite Four!$"

PalletTown_Text_Aliza_BattleDeclined::
    .string "No worries! Come back when you are\n"
    .string "ready!$"

PalletTown_Text_Aliza_BattleZeroAsk::
    .string "Hi {PLAYER} - my name is ALIZA!\n"
    .string "I would love to be a rival!\p"
    .string "Want to give it a shot?$"

PalletTown_Text_Aliza_BattleZeroWon::
    .string "That was fun! Come back after every\n"
    .string "badge to test your strength!$"

PalletTown_Text_Aliza_BattleOneAsk::
    .string "Brock told me you beat him?\n"
    .string "Thats your first badge! Nice!\p"
    .string "Want to see if you are really ready \n"
    .string "to go for the others?$"

PalletTown_Text_Aliza_BattleOneWon::
    .string "That was fun! Come back after every\n"
    .string "badge to test your strength!$"

PalletTown_Text_Aliza_BattleTwoAsk::
    .string "My Pikachu and I will shock you with\n" 
    .string "our strength!\p"
    .string "{PLAYER}, are your charged up?$"

PalletTown_Text_Aliza_BattleTwoWon::
    .string "After that, you can totally take on\n"
    .string "Misty!$"

PalletTown_Text_Aliza_BattleThreeAsk::
    .string "{RIVAL} told me you whooped him on\n"
    .string "SS Anne? Wow, you are really good!\p"
    .string "But are you better than me?$"

PalletTown_Text_Aliza_BattleThreeWon::
    .string "If my Pikachu cannot do it, Lt. Surge is \n" 
    .string "going to have his hands full with you!$"


PalletTown_Text_Aliza_BattleFourAsk::
    .string "{RIVAL} has been keeping me up on\n"
    .string "your journey - I am so proud of your\p"
    .string "progress!\p"
    .string "Ready to see if it is really enough?$"

PalletTown_Text_Aliza_BattleFourWon::
    .string "{PLAYER}, you are turning into \n"
    .string "quite the trainer!$"

PalletTown_Text_Aliza_BattleFiveAsk::
    .string "Ever seen a Snorlax before?$"

PalletTown_Text_Aliza_BattleFiveWon::
    .string "Wow, {PLAYER} - you are getting\n" 
    .string "really good!$"

PalletTown_Text_Aliza_BattleSixAsk::
    .string "{PLAYER}, I am ready for you!\n"
    .string "I have a few surprises up my sleeve!\p"
    .string "Want to go?$"

PalletTown_Text_Aliza_BattleSixWon::
    .string "The way you are going, every gym\n"
    .string "leader needs to watch out!$"

PalletTown_Text_Aliza_BattleSevenAsk::
    .string "{PLAYER}, you took down Team Rocket???\p"
    .string "Now I need to see how I fare against\n" 
    .string "you.\p"
    .string "Are you ready?$"

PalletTown_Text_Aliza_BattleSevenWon::
    .string "Nice work, {PLAYER}! Now go get\n"
    .string "that last badge!$"

PalletTown_Text_Aliza_BattleEightAsk::
    .string "{PLAYER}, I heard you got the Earth\n"
    .string "Badge!\p"
    .string "That means you can challenge the\n" 
    .string "Elite Four!\p"
    .string "Before you do, do you want a final\n"
    .string "challenge?$"

PalletTown_Text_Aliza_BattleEightWon::
    .string "You are so impressive, {PLAYER}!\n"
    .string "Good luck with the Elite 4!$"

PalletTown_Text_TownSign::
    .string "PALLET TOWN\n"
    .string "Shades of your journey await!$"

PalletTown_Text_OakLetMeSeePokedex::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "You're back, are you?\p"
    .string "How much have you filled in your\n"
    .string "POKéDEX?\p"
    .string "May I see it?\p"
    .string "Let's see…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
    .string "You've caught {STR_VAR_2}…\p"
    .string "Hm, it looks as if you're putting\n"
    .string "in an honest effort.\p"
    .string "When you manage to fill it some\n"
    .string "more, come show me, please.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
    .string "You've caught… {STR_VAR_2}!?\n"
    .string "Now, this is impressive!\p"
    .string "There's something I wanted to ask\n"
    .string "of you, {PLAYER}.\p"
    .string "Come.\n"
    .string "Follow me.$"

PalletTown_Text_OakYouEnjoyingTraveling::
    .string "OAK: Ah, {PLAYER}!\n"
    .string "You seem to be enjoying traveling.\p"
    .string "Knowing you, {PLAYER}, I can easily\n"
    .string "imagine you going out to even more\l"
    .string "exotic locales.\p"
    .string "Good for you, good for you.\n"
    .string "Hohoho.$"
